created generic context, modified all needed files
kacgrzes/expo-typescript-template pull request #26
Opened 2022-08-09 11:11 UTC by zagoorland

- created generic context with generator
- modified AuthContext
- deleted useAuth hook, since it's exported from AuthProvider
- changed import path for all the files using useAuth

2022-08-11 10:59 UTC, kacgrzes requested changes

2022-08-11 10:59 UTC, kacgrzes commented on src/navigation/RootNavigator.tsx
> +import { useAuth } from '~providers'
Our code structure has programmer expect to have hooks within `~hooks` directory. I think that you could use `createGenericContext` within `context` directory and reexport `AuthProvider` in `providers` dir and `useAuth` in `hooks` dir.

2022-08-16 12:56 UTC, kacgrzes approved these changes

2022-08-16 12:57 UTC, kacgrzes commented
Looking good!

2022-08-25 10:46 UTC, MateuszRostkowski approved these changes

2022-08-25 10:50 UTC, merged